
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.passaro.mypallene.core;

/**
 * CUP generated interface containing symbol constants.
 */
public interface ParserSym {
    /* terminals */
    public static final int FUNCTION = 2;
    public static final int GE = 41;
    public static final int UMINUS = 49;
    public static final int SLPAR = 29;
    public static final int SEMI = 32;
    public static final int INT = 21;
    public static final int EXECUTE = 19;
    public static final int MINUS = 46;
    public static final int FOR = 10;
    public static final int BRPAR = 28;
    public static final int WRITE = 14;
    public static final int NOT = 16;
    public static final int AND = 34;
    public static final int LT = 36;
    public static final int RPAR = 26;
    public static final int NOP = 44;
    public static final int NIL = 20;
    public static final int OR = 35;
    public static final int BOOL = 22;
    public static final int COMMA = 31;
    public static final int DIV = 48;
    public static final int FLOAT_CONST = 51;
    public static final int PLUS = 45;
    public static final int ASSIGN = 43;
    public static final int MAIN = 3;
    public static final int IF = 5;
    public static final int ID = 18;
    public static final int LE = 37;
    public static final int EOF = 0;
    public static final int RETURN = 15;
    public static final int TRUE = 53;
    public static final int INT_CONST = 50;
    public static final int error = 1;
    public static final int GLOBAL = 12;
    public static final int SRPAR = 30;
    public static final int EQ = 38;
    public static final int TIMES = 47;
    public static final int ARROW = 42;
    public static final int COLON = 33;
    public static final int ELSE = 7;
    public static final int SHARP = 17;
    public static final int READ = 13;
    public static final int WHILE = 8;
    public static final int BLPAR = 27;
    public static final int FLOAT = 23;
    public static final int THEN = 6;
    public static final int NE = 39;
    public static final int END = 4;
    public static final int LPAR = 25;
    public static final int STRING = 24;
    public static final int LOCAL = 11;
    public static final int FALSE = 54;
    public static final int STRING_CONST = 52;
    public static final int GT = 40;
    public static final int DO = 9;
    public static final String[] terminalNames = new String[]{
            "EOF",
            "error",
            "FUNCTION",
            "MAIN",
            "END",
            "IF",
            "THEN",
            "ELSE",
            "WHILE",
            "DO",
            "FOR",
            "LOCAL",
            "GLOBAL",
            "READ",
            "WRITE",
            "RETURN",
            "NOT",
            "SHARP",
            "ID",
            "EXECUTE",
            "NIL",
            "INT",
            "BOOL",
            "FLOAT",
            "STRING",
            "LPAR",
            "RPAR",
            "BLPAR",
            "BRPAR",
            "SLPAR",
            "SRPAR",
            "COMMA",
            "SEMI",
            "COLON",
            "AND",
            "OR",
            "LT",
            "LE",
            "EQ",
            "NE",
            "GT",
            "GE",
            "ARROW",
            "ASSIGN",
            "NOP",
            "PLUS",
            "MINUS",
            "TIMES",
            "DIV",
            "UMINUS",
            "INT_CONST",
            "FLOAT_CONST",
            "STRING_CONST",
            "TRUE",
            "FALSE"
    };
}

